"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import configparser
from setuptools import setup

APP = ['pycast.py']
DATA_FILES = ['assets', 'assets/doors', 'assets/object', 'assets/pickup', 'assets/system', 'assets/walls', 'assets/weapons', 'assets/weapons/blast', 'levels','Camera.py', 'Format.py', 'Global.py', 'LevelCreator.py', 'NPC.py', 'Pycast.py', 'Render.py', 'Weapon.py', 'Door.py', 'gfx.conf']

#Search config file for other weapons and npcs to append to DATA_FILES
cfg = configparser.ConfigParser()
cfg.read('gfx.conf')

#Look for NPCs to include
for option in cfg['SPRITES']:
    if int(option) > 1999 and int(option) <= 2999:
        DATA_FILES.append('assets/npc/' + option + '/alive')
        DATA_FILES.append('assets/npc/' + option + '/dead')

#Look for weapons to include
for option in cfg['WEAPONS']:
    DATA_FILES.append('assets/weapons/weapon_' + option)

OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
