"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pycast.py']
DATA_FILES = ['assets', 'assets/doors', 'assets/npc', 'assets/object', 'assets/pickup', 'assets/system', 'assets/walls', 'assets/weapons', 'assets/weapons/blast', 'assets/weapons/weapon_1', 'assets/weapons/weapon_2', 'levels', 'Camera.py', 'Format.py', 'Global.py', 'LevelCreator.py', 'NPC.py', 'Pycast.py', 'Render.py', 'Weapon.py', 'Door.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
