"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pycast.py']
DATA_FILES = ['assets', 'levels', 'Camera.py', 'Format.py', 'Global.py', 'LevelData.py', 'Map.py', 'LevelCreator.py', 'NPC.py', 'Pycast.py', 'Render.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
